Allow customized NickServ and ChanServ
google/alertmanager-irc-relay pull request #16
Opened 2022-10-08 16:06 UTC by erikmack

DALnet requires interacting with NickServ@services.dal.net and ChanServ@services.dal.net instead of the traditional server-local NickServ and ChanServ.  This PR allows setting the custom values.

2022-10-10 08:25 UTC, shammash commented
Thank you Erik for your contribution. The change looks good and I would like to to merge it, but in order to do so Google requires contributors to sign the CLA (see the bot comment above). If you are unwilling to sign please let me know: We can close this merge request and I will add the feature in another commit.

2022-10-15 19:13 UTC, erikmack commented
Thanks @shammash ... I think I signed the CLA after I saw the notice.  Can the workflow be refreshed/resubmitted?

2022-10-17 13:15 UTC, shammash commented on config.go
> +		NickservName:    "NickServ",
Can you please add NickservName and ChanservName to the config used in the tests? See https://github.com/google/alertmanager-irc-relay/blob/master/irc_test.go#L41

2022-10-17 13:16 UTC, shammash requested changes
Thank you Erik, just one small comment to ensure the tests are passing.
I'll cut a release after merging.

2022-10-19 09:01 UTC, merged